version: '3.8'
services:
  # "cosmosdb" is the name of the Docker Compose service, and is also used as the hostname for incoming connections
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    environment:
      # Low partition count to speed startup (note: will actually create 2 partitions)
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 1
      # Save data across starts
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: 'true'
      # Make sure the emulator lists "cosmosdb" as an alternative name in the cert
      AZURE_COSMOS_EMULATOR_ARGS: '/alternativenames=cosmosdb'
      AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE: '${HOST_IP}'
    # Keep data on the host in ./cosmosdata
    volumes:
      - type: bind
        source: ./cosmosdata
        target: /tmp/cosmos/appdata
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
      - target: 10251
        published: 10251
        protocol: tcp
        mode: host
      - target: 10252
        published: 10252
        protocol: tcp
        mode: host
      - target: 10253
        published: 10253
        protocol: tcp
        mode: host
      - target: 10254
        published: 10254
        protocol: tcp
        mode: host
